export const teams = [
  { name: "Arsenal", code: "afc" },
  { name: "Manchester City", code: "city" },
  { name: "Manchester United", code: "manu" },
  { name: "Liverpool", code: "liv" },
  { name: "Aston Villa", code: "asv" },
  { name: "Tottenham", code: "tot" },
  { name: "Chelsea", code: "cfc" },
  { name: "Newcastle", code: "nfc" },
  { name: "West Ham", code: "whfc" },
  { name: "Crystal Palace", code: "cry" },
  { name: "Brighton", code: "bri" },
  { name: "Bournemouth", code: "bou" },
  { name: "Fulham", code: "ful" },
  { name: "Wolves", code: "wfc" },
  { name: "Everton", code: "eve" },
  { name: "Brentford", code: "bfc" },
  { name: "Nottingham Forest", code: "nf" },
  { name: "Luton", code: "lut" },
  { name: "Burnley", code: "bur" },
  { name: "Sheffield Utd", code: "she" },
  { name: "Bayern Munich", code: "bay" },
  { name: "Lens", code: "rcl" },
  { name: "PSV", code: "psv" },
  { name: "Séville", code: "sev" },
  { name: "Porto", code: "por" },
  { name: "Bolton", code: "bol" },
  { name: "Leicester", code: "lei" },
  { name: "Paris", code: "psg" },
  { name: "Southampton", code: "sou" },
  { name: "Preston", code: "pre" },
  { name: "Shaktar", code: "sha" },
  { name: "Sporting", code: "spo"}
];

export const competitions = [
  "Premier League",
  "Champions League",
  "FA Cup",
  "EFL Cup",
  "Community Shield",
];
