name: Test, compile and push client and server to staging

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  build-and-push-server:
    uses: gwenael9/my-arsenal-app/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: my-arsenal-app/arsenal-app-back

  build-and-push-client:
    uses: gwenael9/my-arsenal-app/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: my-arsenal-app/arsenal-app-front

  notify-vps:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.arsenal-goals.dev/hooks/update-staging-arsenal-app"
